### ISSUE TITLE
Error when setting up lowpass filter

### ISSUE THREAD

**Issue by demoneaux** [berndporr/iirj#2]
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                          at uk.me.berndporr.iirj.LayoutBase.add(LayoutBase.java:57)
                                                                          at uk.me.berndporr.iirj.Butterworth$AnalogLowPass.design(Butterworth.java:58)
                                                                          at uk.me.berndporr.iirj.Butterworth.setupLowPass(Butterworth.java:66)
                                                                          at uk.me.berndporr.iirj.Butterworth.lowPass(Butterworth.java:87)
                                                                          at sg.edu.sutd.syncbeat.utilities.Adaptiv.<init>(Adaptiv.java:17)
                                                                          at sg.edu.sutd.syncbeat.MainActivity.onCreate(MainActivity.java:56)
                                                                          at android.app.Activity.performCreate(Activity.java:5411)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:149) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5257) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                          at dalvik.system.NativeStart.main(Native Method)
```

Looking at https://github.com/berndporr/iirj/blob/master/src/main/java/uk/me/berndporr/iirj/LayoutBase.java#L45 and https://github.com/berndporr/iirj/blob/master/src/main/java/uk/me/berndporr/iirj/LayoutBase.java#L57, it seems like there will always be an array out of bounds error. Is this a bug?

**Comment by berndporr** [comment]
Sorry but without your code it's impossible to reproduce it. Can you tell me how you have initialized the filter?

**Comment by berndporr** [comment]
I've managed to make it crash with odd filter numbers. I've fixed it. However, please use even filter orders because the filter is a cascade of biquads (2nd order filters). If you use an odd order then you wasting computing time because you'd get another order for the same amount of computing.

**Comment by demoneaux** [comment]
Thanks for the help!

**Comment by berndporr** [comment]
Pleasure! :+1:
